### ISSUE TITLE
Feature: 게임 엔진 개발

### ISSUE THREAD

**Issue by Yeonwu** [20th-centuary-meseum/uno-render#9]
- [ ] 상호작용 개발 (히트박스 등)
- [ ] 블럭 부수는거
- [x] 스프라이트 움직임

**Comment by redpotion21** [comment]
블럭 부스는 것에 대해
맵 상의 모든 블럭을, 맵으로 취급하는 것이 아닌, 스프라이트로 취급하여 히트박스에 닿으면 부숴지는 형식으로 하자!

**Comment by Yeonwu** [comment]
블럭은 움직이지도 않고, 상호작용이 닿으면 부서지는 거 하나밖에 없으니 
- 타일 : 고정, 상호작용 X
- 블럭 : 고정, 상호작용 1개
- 스프라이트 : 이동, 상호작용 다수
이렇게 3개로 나누는게 어떨까?

스프라이트는 이동하기 때문에 화면 밖으로 나가는 예외처리가 필요하고, 따라서 리소스 소모가 많아진다.
블럭은 고정되어 있기 때문에 스프라이트로 처리하는 것보다 따로 처리하는게 좋을 것 같다.

아니면 블럭도 스프라이트로 포함시키고 이렇게 할 수도 있을 것 같다.

class Sprite <= 히트박스를 갖는 모든 객체들
class MovableSprite : public Sprite <= 히트박스를 갖고 움직이는 모든 객체들

**Comment by redpotion21** [comment]
오오 이런게 가능하네. 역시 객체지향인가 ㅋㅋ 저걸로 하자!!!!

**Comment by redpotion21** [comment]
오오 이런게 가능하네. 역시 객체지향인가 ㅋㅋ

https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection

히트박스 탐지에 대해 좋은 것 찾음!! 히트박스를 원으로 바꾸어 점과 점 거리 쓰는것 같음!

**Comment by Yeonwu** [comment]
굿굿! AABB도 괜찮을 듯?

https://kareus.tistory.com/15
